# Generated by Django 2.2.12 on 2022-02-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(help_text='CI', max_length=50)),
                ('nombre', models.CharField(help_text='Nombre', max_length=200)),
                ('apellidos', models.CharField(help_text='Apellidos', max_length=200)),
                ('pais', models.CharField(help_text='País', max_length=200)),
                ('provincia', models.CharField(help_text='Provincia', max_length=200)),
                ('municipio', models.CharField(help_text='Municipio', max_length=200)),
                ('situacion_academica', models.CharField(help_text='Situación Académica', max_length=200)),
                ('estado', models.CharField(help_text='Estado', max_length=200)),
                ('direccion', models.CharField(help_text='Dirección', max_length=1000)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('carrera', models.CharField(help_text='Carrera', max_length=500)),
                ('facultad', models.CharField(help_text='Facultad', max_length=200)),
                ('tipo_curso', models.CharField(help_text='Tipo de curso', max_length=200)),
                ('correo', models.CharField(help_text='Correo electrónico', max_length=200)),
                ('fuente_ingreso', models.CharField(help_text='Fuente de Ingreso', max_length=200)),
                ('origen_academico', models.CharField(help_text='Origen Académico', max_length=200)),
                ('regimen_estudio', models.CharField(help_text='Regimen de Estudio', max_length=200)),
                ('natural_de', models.CharField(help_text='Natural de', max_length=200)),
                ('telefono', models.CharField(help_text='Teléfono', max_length=200)),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso a la ES')),
                ('estado_civil', models.CharField(help_text='Estado Civil', max_length=200)),
                ('organizacion_politica', models.CharField(help_text='Organización política', max_length=200)),
                ('fecha_ingreso_ces', models.DateField(verbose_name='Fecha de ingreso al Ces')),
                ('fecha_matricula', models.DateField(verbose_name='Fecha de matrícula')),
                ('sexo', models.CharField(help_text='Sexo', max_length=200)),
                ('color_piel', models.CharField(help_text='Color de la piel', max_length=200)),
                ('tipo_estudiante', models.CharField(help_text='Tipo de estudiante', max_length=200)),
                ('anho_estudio', models.IntegerField(help_text='Año de Estudio')),
                ('centro_trabajo', models.CharField(help_text='Centro de Trabajo', max_length=200)),
                ('nombre_padre', models.CharField(help_text='Nombre del Padre', max_length=500)),
                ('nivel_academico_padre', models.CharField(help_text='Nivel Academico del Padre', max_length=200)),
                ('nombre_madre', models.CharField(help_text='Nombre de la Madre', max_length=500)),
                ('nivel_academico_madre', models.CharField(help_text='Nivel academico de la madre', max_length=200)),
                ('tipo_servicio_militar', models.CharField(help_text='Tipo de servicio militar', max_length=200)),
                ('edad', models.IntegerField(verbose_name='Edad')),
            ],
        ),
    ]
