# Generated by Django 2.2.12 on 2022-02-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nombre',
            field=models.CharField(help_text='Nombre', max_length=200, null=True),
        ),
    ]
