# Generated by Django 2.2.12 on 2022-02-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsInfo', '0002_auto_20220210_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='anho_estudio',
            field=models.IntegerField(help_text='Año de Estudio', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='apellidos',
            field=models.CharField(help_text='Apellidos', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='carrera',
            field=models.CharField(help_text='Carrera', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='centro_trabajo',
            field=models.CharField(help_text='Centro de Trabajo', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='color_piel',
            field=models.CharField(help_text='Color de la piel', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='correo',
            field=models.CharField(help_text='Correo electrónico', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='direccion',
            field=models.CharField(help_text='Dirección', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='edad',
            field=models.IntegerField(null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='student',
            name='estado',
            field=models.CharField(help_text='Estado', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='estado_civil',
            field=models.CharField(help_text='Estado Civil', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='facultad',
            field=models.CharField(help_text='Facultad', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fecha_ingreso',
            field=models.DateField(null=True, verbose_name='Fecha de Ingreso a la ES'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fecha_ingreso_ces',
            field=models.DateField(null=True, verbose_name='Fecha de ingreso al Ces'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fecha_matricula',
            field=models.DateField(null=True, verbose_name='Fecha de matrícula'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fuente_ingreso',
            field=models.CharField(help_text='Fuente de Ingreso', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='municipio',
            field=models.CharField(help_text='Municipio', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='natural_de',
            field=models.CharField(help_text='Natural de', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nivel_academico_madre',
            field=models.CharField(help_text='Nivel academico de la madre', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nivel_academico_padre',
            field=models.CharField(help_text='Nivel Academico del Padre', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nombre_madre',
            field=models.CharField(help_text='Nombre de la Madre', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nombre_padre',
            field=models.CharField(help_text='Nombre del Padre', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='organizacion_politica',
            field=models.CharField(help_text='Organización política', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='origen_academico',
            field=models.CharField(help_text='Origen Académico', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pais',
            field=models.CharField(help_text='País', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='provincia',
            field=models.CharField(help_text='Provincia', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='regimen_estudio',
            field=models.CharField(help_text='Regimen de Estudio', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sexo',
            field=models.CharField(help_text='Sexo', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='situacion_academica',
            field=models.CharField(help_text='Situación Académica', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='telefono',
            field=models.CharField(help_text='Teléfono', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='tipo_curso',
            field=models.CharField(help_text='Tipo de curso', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='tipo_estudiante',
            field=models.CharField(help_text='Tipo de estudiante', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='tipo_servicio_militar',
            field=models.CharField(help_text='Tipo de servicio militar', max_length=200, null=True),
        ),
    ]
