# Generated by Django 2.2.12 on 2022-02-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsInfo', '0004_auto_20220210_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='apellidos',
            field=models.CharField(default='desconocido', help_text='Apellidos', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='pais',
            field=models.CharField(help_text='País', max_length=200),
        ),
    ]
